### ISSUE TITLE
pypi version very old ?

### ISSUE THREAD

**Issue by leplatrem** [nickoala/telepot#1]
Just so that you know... The package seems to be outdated on pypi and fails on install :) 

```
pip install telebot
Downloading/unpacking telebot
  Downloading telebot-0.0.2.tar.gz
  Storing download in cache at /home/mathieu/Downloads/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Ft%2Ftelebot%2Ftelebot-0.0.2.tar.gz
  Running setup.py (path:/tmp/pip-build-j0hVco/telebot/setup.py) egg_info for package telebot
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-j0hVco/telebot/setup.py", line 6, in <module>
        readme = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-j0hVco/telebot/setup.py", line 6, in <module>

    readme = open('README.md').read()

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-j0hVco/telebot
Storing debug log for failure in /home/mathieu/.pip/pip.log

```

**Comment by nickoala** [comment]
Well, you were downloading telebot. My library is telepot. I guess that closes the issue.
