### ISSUE TITLE
'Session is closed' errors

### ISSUE THREAD

**Issue by juanfont** [nickoala/telepot#108]
Hi,

I am a really happy user of telepot. Amazing library, amazing code. I am using it for a async DelegatorBot-based bot.

The thing is that since three days ago I am getting random 'Session is closed' errors. The bot works normally until without any warning starts prompting this errors:

> RuntimeError: Session is closed
> Traceback (most recent call last):
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/aiohttp/client.py", line 187, in _request
>     yield from resp.start(conn, read_until_eof)
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 606, in start
>     message = yield from httpstream.read()
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/aiohttp/streams.py", line 591, in read
>     result = yield from super().read()
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/aiohttp/streams.py", line 446, in read
>     yield from self._waiter
>   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 297, in _wakeup
>     future.result()
>   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
>     raise self._exception
> aiohttp.errors.ServerDisconnectedError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/telepot/async/__init__.py", line 228, in get_from_telegram_server
>     result = await self.getUpdates(offset=offset, timeout=20)
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/telepot/async/__init__.py", line 168, in getUpdates
>     return await self._api_request('getUpdates', _rectify(p))
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/telepot/async/__init__.py", line 38, in _api_request
>     return await api.request((self._token, method, params, files), **kwargs)
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/telepot/async/api.py", line 108, in request
>     async with fn(*args, **kwargs) as r:
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/aiohttp/client.py", line 539, in __aenter__
>     self._resp = yield from self._coro
>   File "/home/ubuntu/politibot/lib/python3.5/site-packages/aiohttp/client.py", line 150, in _request
>     raise RuntimeError('Session is closed')

Do you have any idea of what can it be? Is anyone around having the same issue?

**Comment by mode2k** [comment]
I do have similar errors.

File: /usr/lib/python3.5/ssl.py, Line: 571, Method: read, Exception: ('Connection aborted.', ConnectionResetError(104, 'Die Verbindung wurde vom Kommunikationspartner zurückgesetzt'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 925, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 787, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 571, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    self._bot.sendMessage(receiverID, message)
  File "/usr/local/lib/python3.5/dist-packages/telepot-8.1-py3.5.egg/telepot/__init__.py", line 235, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python3.5/dist-packages/telepot-8.1-py3.5.egg/telepot/__init__.py", line 224, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telepot-8.1-py3.5.egg/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/poolmanager.py", line 248, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/util/retry.py", line 238, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.16-py3.5.egg/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 925, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 787, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 571, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Die Verbindung wurde vom Kommunikationspartner zurückgesetzt'))

After this i got this in my log:
2016-06-30 12:29:12 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 13:02:45 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 13:36:18 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 14:09:51 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 14:43:24 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 15:16:57 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 15:50:29 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 16:24:03 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 16:57:36 INFO     Thread-6     Resetting dropped connection: api.telegram.org
2016-06-30 17:31:09 INFO     Thread-6     Resetting dropped connection: api.telegram.org

**Comment by mode2k** [comment]
My Prob seems to be like in #87
Using 7.1. now....

**Comment by ttsda** [comment]
This is happening to me. My bots run for a day or two until it happens.

**Comment by nickoala** [comment]
As detailed in #87, it may be the version of `urllib3`. Try downgrade it to 1.9.1, and see what happen.

**Comment by nickoala** [comment]
As mentioned in #87, making `retries=3` solves the problem.
