### ISSUE TITLE
cant send big photos

### ISSUE THREAD

**Issue by matze19999** [nickoala/telepot#135]
If I want to send a photo with 4,29mb and 9702x7168 I get a error.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 738, in collector
    callback(item)
  File "/home/pi/diceyclock.py", line 26, in handle
    bot.sendPhoto(chat_id, f)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 448, in sendPhoto
    return self._sendfile(photo, 'photo', p)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 429, in _sendfile
    return self._api_request(method, _rectify(params), files)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u'PHOTO_INVALID_DIMENSIONS', 400, {u'error_code': 400, u'ok': False, u'description': u'PHOTO_INVALID_DIMENSIONS'})

**Comment by zumoshi** [comment]
Hello,
this is not a telepot error, it's a telegram api limitation.

see also: 

- https://core.telegram.org/api/errors#400-bad-request
- https://github.com/zhukov/webogram/issues/726

I couldn't really find max valid dimensions for images in telegram, but have you tried sending it with `sendDocument` method instead? that one has no limit on the image size/dimensions.
alternatively, you can resize your image if you want the thumbnail to show up.

**Comment by matze19999** [comment]
nice, I will test it today :)
