### ISSUE TITLE
EventNotFound

### ISSUE THREAD

**Issue by efazati** [nickoala/telepot#140]
whats the problem?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/delegate.py", line 255, in wait_loop
    j.on_message(msg)
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 532, in augmented
    is_event(msg) or self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 524, in refresh
    self._scheduler.cancel(self._timeout_event)
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 613, in cancel
    return self._base.cancel(event)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 357, in cancel
    self._remove_event(event)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 281, in k
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 310, in _remove_event
    raise exception.EventNotFound(event)
EventNotFound: Event(timestamp=1472395131.718516, data={'_idle': {'seconds': 10, 'source': {'id': 250877155, 'space': 1}}})

```

**Comment by nickoala** [comment]
How often does it happen?

**Comment by efazati** [comment]
i dont have any clue... every 2 hours this happend

**Comment by oc2pcoj** [comment]
``` Traceback (most recent call last):
_idle
File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/delegate.py", line 255, in wait_loop
    j.on_message(msg)
  File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/helper.py", line 532, in augmented
    is_event(msg) or self.refresh()
  File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/helper.py", line 524, in refresh
    self._scheduler.cancel(self._timeout_event)
  File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/helper.py", line 613, in cancel
    return self._base.cancel(event)
  File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/__init__.py", line 357, in cancel
    self._remove_event(event)
  File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/__init__.py", line 281, in k
    return fn(self, *args, **kwargs)
  File "mypathtovenv/venv/lib/python2.7/site-packages/telepot/__init__.py", line 310, in _remove_event
    raise exception.EventNotFound(event)
EventNotFound: Event(timestamp=1474189285.112213, data={'_idle': {'seconds': 10, 'source': {'id': 110821612, 'space': 1}}})
```
What is '_idle'? I can handle correct one message from bot. After this I have got `_idle` flavor. And next message from bot raise  `EventNotFound` exception.

**Comment by nickoala** [comment]
@efazati, I made some changes in version 10.0. May you upgrade telepot and see if this problem still occurs?

**Comment by oc2pcoj** [comment]
@nickoala I have tested version 10.0 and it seems that bug is fixed. Thank you!

**Comment by nickoala** [comment]
Cool. I will wait for @efazati's response before closing the issue. Thanks for letting me know.

**Comment by efazati** [comment]
Yes it works
