### ISSUE TITLE
google app engine problem

### ISSUE THREAD

**Issue by pumper** [nickoala/telepot#151]
Hi 
I tried to use your lib with google app engine.
but it fails to load library.
the error log of GAE is :

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  **File "/base/data/home/apps/s~gaetest-58/1.395411486690433439/main.py", line 21, in <module>
    import telepot
ImportError: No module named telepot**
request_id: "57cc8a8a00ff036914124631f00001737e676165746573742d3538000131000100"
timestamp: "2016-09-04T20:56:42.250Z"
location: "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263"
ws

as you can see it says that No module named telepot
what can i do?

**Comment by nickoala** [comment]
Sorry, I don't know. I have not used Google App Engine. Don't they have instructions telling you how to install Python packages on their platform?

**Comment by Serafim-End** [comment]
where did you install library. 
I have just install it to lib/ path in the root of my project and write to appengine_config.py 

from google.appengine.ext import vendor
vendor.add('lib')

and it works fine.

**Comment by nickoala** [comment]
So, you got your problem solved?

**Comment by pumper** [comment]
I solved th eproblem with the method that Serafim-End told.I found the solution on the app engine docs.
thanks all.
but when i wan to use the getMe method i get the following errors:

nternal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/main.py", line 29, in get
    self.response.write(pprint(bot.getMe()))
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/telepot/__init__.py", line 402, in getMe
    return self._api_request('getMe')
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/urllib3/poolmanager.py", line 248, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/urllib3/connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "/base/data/home/apps/s~tciadsbot/1.395427594842325429/lib/urllib3/connectionpool.py", line 808, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
SSLError: Can't connect to HTTPS URL because the SSL module is not available.

i use the method this way:
self.response.write(bot.getMe())

**Comment by nickoala** [comment]
> SSLError: Can't connect to HTTPS URL because the SSL module is not available.

No SSL module installed?

Don't ask me how to do it. I have not used GAE :smile:

**Comment by pumper** [comment]
I solved ssl problem using the methd described in the gae docs:

Specifying the SSL library:

If you want to use native python SSL, you must enable it using the libraries configuration in your application's app.yaml file where you specify the library name "ssl". There are two libraries available, version 2.7 supports TLS v1.0 only:

libraries:
- name: ssl
  version: 2.7
Version 2.7.11 supports TLS v1.0, v1.1, and v1.2:

libraries:
- name: ssl
  version: 2.7.11
 the ssl error solved but it ask me to enable billing in the gae console.
is there any other app engine out there with easier using methods and features like google or better solution?

**Comment by nickoala** [comment]
To be honest with you, how to pick a host is outside the scope of this space. The web should be full of advice of this kind. Just to give a few simple suggestions: Heroku, Webfaction are what I can think of immediately. Beware that learning how to do things on a platform is always a process. Don't expect it to be smooth or easy, especially for novices.

**Comment by pumper** [comment]
thanks all.
this problem  solved
