### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by ilovetobowl** [nickoala/telepot#157]
I'm trying to send messages with Chinese characters but can't seem to get it to work. Is it not supported at the moment?

**Comment by zumoshi** [comment]
Hello,
are you using python 2 ?
telepot has no problem with utf-8 characters , see issue #149
you most likely have problems with utf support in python 2, try putting a `u` before your strings, so instead of `'何'` , write `u'何'`, or even better , upgrade to python 3 which has native unicode support and all strings are utf-8 by default.

**Comment by ilovetobowl** [comment]
Yes I'm using Python 2 as I'm trying to modify some script which was written on that version. I tried the u method but was still getting errors.

**Comment by zumoshi** [comment]
can you please post the error messages and the line numbers that caused the error?
without more information, we can't really help you.

**Comment by ilovetobowl** [comment]
This is what I got when I tried sendMessage with just one Chinese character:

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1397, in run
    telebot.sendMessage(chat_id=telegram, text= u'\u5751', parse_mode= 'HTML',disable_web_page_preview='False',disable_notification='False')
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 409, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "C:\Python27\lib\site-packages\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 83: ordinal not in range(128)

**Comment by nickoala** [comment]
Can you just try it like this (after substituting the **token** and **user id**):
```python
import telepot
bot = telepot.Bot(TOKEN)
bot.sendMessage(999999999, u'我愛保齡球')
```
And see what happens?

**Comment by ilovetobowl** [comment]
Hey that actually worked! Now I need to find out why it didn't work in the other program...

**Comment by highcat** [comment]
FYI: with Python2, somehow the api_key shouldn't be unicode:

    bot = telepot.Bot(bot_model.api_key) # bot_model.api_key gives unicode
    bot.sendMessage(r.recipient_id, u"Авторизация успешна")

    >> 'ascii' codec can't decode byte 0xd0 in position 83: ordinal not in range(128)

Yet this works:

    bot = telepot.Bot(bot_model.api_key.encode('utf-8'))
    bot.sendMessage(r.recipient_id, u"Авторизация успешна")
