### ISSUE TITLE
Can't detect a invalid Token.

### ISSUE THREAD

**Issue by xTheGamerBRx** [nickoala/telepot#16]
I'm are creating a script that permits the user select his token.
When i do it:
```python
	try:
		bot.notifyOnMessage(handle)
	except:
		error_msg('Invalid token.')
```
I receive this giant error:
```text
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 237, in _parse
    data = response.json()
  File "C:\Python34\lib\site-packages\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 427, in run
    result = get_updates(offset=offset, timeout=self.timeout)
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 374, in get_updates
    return self.getUpdates(offset=offset, timeout=timeout)
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 332, in getUpdates
    return self._parse(r)
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 239, in _parse
    raise BadHTTPResponse(response.status_code, response.text)
telepot.BadHTTPResponse: (200, 'telegram\'s default api docs page here')```

How i solve it?

**Comment by nickoala** [comment]
It looks like telegram servers returned some non-JSON data. Did you try:

```
bot.getMe()
```

to make sure your token is correct?

**Comment by xTheGamerBRx** [comment]
Thanks so much, bro!
After Reading your response, i tried this:
```python
import telepot

bot = telepot.Bot('error')
try:
	a = bot.getMe()
except telepot.BadHTTPResponse:
	print('error!')
```
And my cmd returned 'error'. Well, it Works!
Thanks!
