### ISSUE TITLE
Cannot connect to host

### ISSUE THREAD

**Issue by stleon** [nickoala/telepot#168]
## Long story short

On old version of aiohttp [skeletona.py](https://github.com/nickoala/telepot/blob/master/examples/simple/skeletona.py) all works fine.

```
aiohttp==0.22.5
telepot==9.1
```

But when I use `aiohttp==1.0.3` the problems begin
## Expected behaviour

No errors
## Actual behaviour

```
Traceback (most recent call last):
  File "/Users/user/project/venv/lib/python3.5/site-packages/telepot/aio/__init__.py", line 409, in get_from_telegram_server
    result = await self.getUpdates(offset=offset, timeout=timeout)
  File "/Users/user/project/venv/lib/python3.5/site-packages/telepot/aio/__init__.py", line 292, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "/Users/user/project/venv/lib/python3.5/site-packages/telepot/aio/__init__.py", line 66, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "/Users/user/project/venv/lib/python3.5/site-packages/telepot/aio/api.py", line 112, in request
    async with fn(*args, **kwargs) as r:
  File "/Users/user/project/venv/lib/python3.5/site-packages/aiohttp/client.py", line 565, in __aenter__
    self._resp = yield from self._coro
  File "/Users/user/project/venv/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/Users/user/project/venv/lib/python3.5/site-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 65] Cannot connect to host api.telegram.org:443 ssl:True [Can not connect to api.telegram.org:443 [No route to host]]
```
## Steps to reproduce

```
import asyncio
import os

import telepot
import telepot.aio

def handle(msg):
    flavor = telepot.flavor(msg)

    summary = telepot.glance(msg, flavor=flavor)
    print(flavor, summary)


TOKEN = os.getenv('TOKEN')

bot = telepot.aio.Bot(TOKEN)
loop = asyncio.get_event_loop()

loop.create_task(bot.message_loop(handle))
print('Listening ...')

loop.run_forever()

```
## Mine environment
- macOS Sierra
- Python 3.5.1
- aiodns==1.1.1
- aiohttp==1.0.3

Thanks!

**Comment by nickoala** [comment]
I cannot reproduce this problem. I suspect it was Telegram servers down for a period of time, just after you made that upgrade.

### My environment

- Raspbian Jessie
- Python 3.5.2
- No aiodns
- aiohttp==1.0.3

**Comment by stleon** [comment]
without **aiodns** works too

But in [docs](http://aiohttp.readthedocs.io/en/stable/):

```
For speeding up DNS resolving by client API you may install aiodns as well. This option is highly recommended:
```

**Comment by nickoala** [comment]
Ok. So, with or without aiodns, are you still having this problem?

**Comment by stleon** [comment]
with aiodns I steel having this problem

**Comment by nickoala** [comment]
Yes, **with aiodns installed**, I am having this problem too ....

I have no clue why this happens, and cannot promise when I will investigate it .... so, I will just leave it here, for anyone interested to see and decide on their course of action - either remove aiodns, or use an older version of aiohttp.

**Comment by stleon** [comment]
hey =)

the same problem with 
```
telepot==12.2
aiohttp==2.2.5
```

**Comment by stleon** [comment]
sorry, its problem with mine openssl
