### ISSUE TITLE
BadHTTPResponse

### ISSUE THREAD

**Issue by boscolai1991** [nickoala/telepot#179]
Dear,

I was just listening with the modification from example/simple/skeletona.py and I am pretty sure there was no one submitting message to my bot at that moment or execute my code twice, then it suddenly give me error repeatedly below:

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\__init__.py", line 432, in get_from_telegram_server
    result = await self.getUpdates(offset=offset, timeout=timeout)
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\__init__.py", line 298, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\__init__.py", line 66, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\api.py", line 108, in request
    return await _parse(r)
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\api.py", line 83, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
telepot.exception.BadHTTPResponse: <unprintable BadHTTPResponse object>
Attempt to decode JSON with unexpected mimetype: text/html
Traceback (most recent call last):
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\api.py", line 80, in _parse
    data = await response.json()
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\aiohttp\client_reqrep.py", line 756, in json
    return loads(stripped.decode(encoding))
  File "C:\Users\type_ok_login\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\type_ok_login\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\type_ok_login\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) `

Any idea why did this happen? 

Additionally, this error was only stopped when I manually stopped the run-forever loop. It generated 1 Mb log of the above during the half hour I was not attending my computer. I may not be aware of this error when I am not 'talking' to my bot. Is there some 'protection' mechanism to stop the run-forever loop (and perhaps send me some nice little warning when it stop working)? =]

**Comment by nickoala** [comment]
Sorry, there is no easy way to minimize logging, as detailed in #139.

That error occurred because it did not receive a valid JSON response (thus, the `BadHTTPResponse`). As for why it happened ...... did you supply a wrong token?
