### ISSUE TITLE
Start getting error 

### ISSUE THREAD

**Issue by Smosker** [nickoala/telepot#186]
My bot fall with this error, it works fine for weeks, but now i cant start it, if some how depends on 2.3 update? Can you advise any solution?

2016-11-21T22:16:22.537981+00:00 app[worker.1]: Traceback (most recent call last):
2016-11-21T22:16:22.538008+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telepot/__init__.py", line 761, in get_from_telegram_server
2016-11-21T22:16:22.538010+00:00 app[worker.1]:     offset = max([relay_to_collector(update) for update in result]) + 1
2016-11-21T22:16:22.538012+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telepot/__init__.py", line 761, in <listcomp>
2016-11-21T22:16:22.538013+00:00 app[worker.1]:     offset = max([relay_to_collector(update) for update in result]) + 1
2016-11-21T22:16:22.538027+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telepot/__init__.py", line 748, in relay_to_collector
2016-11-21T22:16:22.538028+00:00 app[worker.1]:     'chosen_inline_result'])
2016-11-21T22:16:22.538030+00:00 app[worker.1]:     raise KeyError(keys)
2016-11-21T22:16:22.538029+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telepot/__init__.py", line 61, in _find_first_key
2016-11-21T22:16:22.538056+00:00 app[worker.1]: KeyError: ['message', 'edited_message', 'callback_query', 'inline_query', 'chosen_inline_result']

**Comment by carloalbertobarbano** [comment]
Refer to this issue: https://github.com/nickoala/telepot/issues/184
