### ISSUE TITLE
UnicodeDecodeError in sendPhoto

### ISSUE THREAD

**Issue by GalPressman** [nickoala/telepot#188]
When trying to send a local photo using a file-like object (from `open`), I get the following trace:
```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/matrix_client/client.py", line 258, in listen_forever
    self._sync(timeout_ms)
  File "build/bdist.linux-x86_64/egg/matrix_client/client.py", line 369, in _sync
    listener['callback'](event)
  File "/home/galp/galp/matrigram/matrix_cli.py", line 57, in on_message
    self.forward_image_from_cli(roomchunk)
  File "/home/galp/galp/matrigram/matrix_cli.py", line 156, in forward_image_from_cli
    self.tb.forward_photo_from_cli(path, self)
  File "/home/galp/galp/matrigram/matrigram.py", line 221, in forward_photo_from_cli
    self.sendPhoto(from_id, open(path, 'rb'))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 448, in sendPhoto
    return self._sendfile(photo, 'photo', p)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 429, in _sendfile
    return self._api_request(method, _rectify(params), files)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 152: invalid start byte
```

Sending the request using telegram api explicitly is my current workaround for this.

**Comment by nickoala** [comment]
```python
import telepot
bot = telepot.Bot('111111111:AAAAAAAAAAAAAAA')
bot.sendPhoto(99999999, open('test/lighthouse.jpg', 'rb'))
```
This works fine for me :blush: 

Someone mentioned sometime ago that, once he did a fresh install of the system, UnicodeDecodeError disappeared. I can't remember which issue exactly, and a search did not turn up the desired result. The thing is, you are not the first one having this issue, but I am not able to help here because I can't reproduce it. Sorry.

**Comment by GalPressman** [comment]
Thanks for the reply,
Just to mention, it happens to me and another person, though both working on the same project.
I'll stick to my workaround for now.
