### ISSUE TITLE
Crash everytime.

### ISSUE THREAD

**Issue by oc2pcoj** [nickoala/telepot#192]
I don't make any changes in code.

```Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/telepot/__init__.py", line 792, in get_from_telegram_server
    offset = max([relay_to_collector(update) for update in result]) + 1
  File "build/bdist.linux-x86_64/egg/telepot/__init__.py", line 779, in relay_to_collector
    'chosen_inline_result'])
  File "build/bdist.linux-x86_64/egg/telepot/__init__.py", line 61, in _find_first_key
    raise KeyError(keys)
KeyError: ['message', 'edited_message', 'callback_query', 'inline_query', 'chosen_inline_result']```

**Comment by oc2pcoj** [comment]
Sorry.  Update to 10.2 fixes this.
