### ISSUE TITLE
KeyError: ['message', 'edited_message', 'callback_query', 'inline_query', 'chosen_inline_result']

### ISSUE THREAD

**Issue by kTweaks** [nickoala/telepot#194]
My bot randomly started throwing this error for every incoming message it received:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 761, in get_from_telegram_server
    offset = max([relay_to_collector(update) for update in result]) + 1
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 761, in <listcomp>
    offset = max([relay_to_collector(update) for update in result]) + 1
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 748, in relay_to_collector
    'chosen_inline_result'])
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 61, in _find_first_key
    raise KeyError(keys)
KeyError: ['message', 'edited_message', 'callback_query', 'inline_query', 'chosen_inline_result']

This error was thrown while it was running, not in between an update, so I don't think it's anything to do with my code.

I tried generating a new HTTP access token to see if that would fix anything but the error is still being thrown for every incoming message

Is there any way to fix this so my bot can return to functionality?

**Comment by R0bertoG** [comment]
I think your issue is the same that this one:
[https://github.com/nickoala/telepot/issues/184]()

Try to upgrade telepot to the last version where the problem has been already solved:

`pip install telepot --upgrade`
