### ISSUE TITLE
Problem with aiohttp

### ISSUE THREAD

**Issue by Dragon-Born** [nickoala/telepot#195]
What's the problem? 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telepot-10.2-py3.5.egg/telepot/aio/__init__.py", line 434, in get_from_telegram_server
    result = await self.getUpdates(offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telepot-10.2-py3.5.egg/telepot/aio/__init__.py", line 298, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python3.5/dist-packages/telepot-10.2-py3.5.egg/telepot/aio/__init__.py", line 65, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telepot-10.2-py3.5.egg/telepot/aio/api.py", line 108, in request
    return await _parse(r)
  File "/usr/local/lib/python3.5/dist-packages/telepot-10.2-py3.5.egg/telepot/aio/api.py", line 82, in _parse
    text = await response.text()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 769, in text
    return self._content.decode(encoding)
UnicodeDecodeError: 'hz' codec can't decode byte 0x7e in position 114: illegal multibyte  
```

**Comment by Imandaneshi** [comment]
There's a temporary fix 
Open `/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py` then go to line 787 change 

```python
if encoding is None:
    encoding = self._get_encoding()
```
to
```python
if encoding is None:
    encoding = "utf-8"
```
