### ISSUE TITLE
Exception after a while

### ISSUE THREAD

**Issue by morellik** [nickoala/telepot#20]
After a while I receive an exception

Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/telepot/__init__.py", line 427, in run
    result = get_updates(offset=offset, timeout=self.timeout)
  File "build/bdist.linux-i686/egg/telepot/__init__.py", line 374, in get_updates
    return self.getUpdates(offset=offset, timeout=timeout)
  File "build/bdist.linux-i686/egg/telepot/__init__.py", line 331, in getUpdates
    r = requests.post(self._methodurl('getUpdates'), params=self._rectify(p), timeout=self._http_timeout+(0 if timeout is None else timeout))
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/adapters.py", line 435, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=50)

Is there a way to solve the problem?

**Comment by nickoala** [comment]
This is because Telegram servers take too long to respond to the `getUpdates` request. If the message loop keeps running (that is, you can still receive messages), there is nothing to worry about.

I found this timeout exception happens more often lately, possibly because the introduction of inline query heightens the servers' workload.

**Comment by morellik** [comment]
Thanks for your answer and for your wonderful work.
