### ISSUE TITLE
Exception in thread Thread-3

### ISSUE THREAD

**Issue by keturiosakys** [nickoala/telepot#201]
_Telepot_ doesn't seem to be running properly on Raspbian Jessie lite.

Here's the error:
````
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 816, in get_from_telegram_server
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'
````

Here's my code:
````
#!/usr/bin/python
# -*- coding: utf-8 -*-

import telepot
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)

relays = [17, 18, 22, 23, 24]
GPIO.setup(relay, GPIO.OUT)
GPIO.output(relay, GPIO.HIGH)

def handle(msg):
    chat_id = msg['chat']['id']
    command = msg['text']

    print 'Got command: %s' % command

    if command == 'main':
        GPIO.output(17, GPIO.LOW)
        bot.sendMessage(chat_id, 'Main heating on')
    elif command == 'saloon':
        GPIO.output(22, GPIO.LOW)
        bot.sendMessage(chat_id, 'Saloon heating on')
    elif command == 'bedroom':
        GPIO.output(18, GPIO.LOW)
        bot.sendMessage(chat_id, 'Bedroom heating on')
    elif command == 'bathroom':
        GPIO.output(23, GPIO.LOW)
        bot.sendMessage(chat_id, 'Bathroom heating on')

bot = telepot.Bot('°°°hidden°°°')
bot.message_loop(handle)
print 'I am listening ...'
````

**Comment by nickoala** [comment]
I think you forgot to add an infinite loop at the end to prevent the program from exiting:

```python
import time
while 1:
    time.sleep(10)
```

**Comment by keturiosakys** [comment]
Thanks! It helped.
