### ISSUE TITLE
Send message to my chat_id

### ISSUE THREAD

**Issue by ilglere** [nickoala/telepot#217]
Hi all,
I'm very newbie in python, so sorry for this (stupid) question.

My bot is running on my raspberry pi and I wish my bot could send a message to my chat_id when it is on.
So: I switch on my raspberry and my bot sends me a message "I'm up!".
Is it possible? Or have I always to send a message to my bot first?

Thanks

**Comment by rescindable** [comment]
Have your bot send you a message with your own user ID 

```
if msg['text'] == '/myid':
    bot.sendMessage(msg['from']['id'], str(msg['from']['id'])
```

Then save that ID as a variable and use it in a static operation before starting your message polling

```
bot.sendMessage(myID, "I'm up!")
```

**Comment by ilglere** [comment]
Hi rescindable,
I've already used this method on my code based on diceyclok.py, as you can see above:
`import os
import time
import random
import datetime
import telepot

my_ID = [11111111] #my telegram ID

def handle(msg):
        chat_id = msg['chat']['id']
        command = msg['text']
        temp = str()

        if chat_id in my_ID: #only my ID can use this bot

                print ('Get it:', command)
                print ('ID code:', chat_id)

                if command == '/start':
                        bot.sendMessage (chat_id, 'Hi Glere!')
                elif command == '/temp':
                        os.system('sudo python3 /var/scripts/get_temp.py')
                        temp = open("/var/scripts/cpu_temp.txt","r")
                        bot.sendMessage(chat_id,temp.readline())
                elif command == '/halt':
                        os.system('sudo halt -h')
                elif command == '/reboot':
                        os.system('sudo reboot')
                elif command == '/restartplex':
                        os.system('sudo /etc/init.d/plexserver restart')
                elif command == '/loadvnc':
                        os.system('vncserver')
                elif command == '/random':
                        bot.sendMessage(chat_id, random.randint(1,99))
                elif command == '/time':
                        bot.sendMessage(chat_id, str(datetime.datetime.now()))
                elif command == 'Foto' or command == 'foto' or command == '/foto':
                        bot.sendPhoto(chat_id, photo=open('/home/pi/TelegramBot/test.jpg', 'rb'))
                elif command == '/update':
                        bot.sendMessage(chat_id, 'Updating...')
                        os.system('sudo apt-get update && sudo apt-get upgrade -y')
                        bot.sendMessage(chat_id, 'Raspy updated')
        else:
                bot.sendMessage(chat_id, 'Permission denied. GTFO')

bot = telepot.Bot('TELEGRAM KEY')
bot.sendMessage(my_ID, "I'm up!")
bot.message_loop(handle)
#print 'Listening...'

while 1:
        time.sleep(10)`

But I'm getting this error message:
`pi@raspberrypi:~ $ python TelegramBot/gleresbot.py
Traceback (most recent call last):
  File "TelegramBot/gleresbot.py", line 48, in <module>
    bot.sendMessage(my_ID, "I'm up!")
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 408, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 397, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: (u'Bad Request: chat not found', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: chat not found'})`

What am I doing wrong?

Thanks!!

**Comment by rescindable** [comment]
It looks like you're trying to send a message using your list variable instead of a string. The easiest solution would be to save the my_id variable as a string, but at the very least you would need to change your code to:

`bot.sendMessage(str(my_id[0]), "I'm up!")`

**Comment by ilglere** [comment]
YOU MADE MY DAY!!
I've solved my issue saving my_if variable as string.

Many thanks rescindable!!
