### ISSUE TITLE
editMessageText Bad Request

### ISSUE THREAD

**Issue by Blank517** [nickoala/telepot#226]
I get this error either in private or on groups. How can I resolve?
```
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    sender = msg['from']['id']
    print(sender)
         if content_type == 'text':
              identity = telepot.origin_identifier(msg)
              bot.editMessageText(identity, "edited")

```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 781, in collector
    callback(item)
  File "bot.py", line 48, in handle
    bot.editMessageText(identity, "edited")
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 598, in editMessageText
    return self._api_request('editMessageText', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 397, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u"Bad Request: message can't be edited", 400, {u'error_code': 400, u'ok': False, u'description': u"Bad Request: message can't be edited"})
```

**Comment by nickoala** [comment]
I think you should use `telepot.message_identifier(msg)`

**Comment by Blank517** [comment]
Same error
```
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    sender = msg['from']['id']
    print(sender)
         if content_type == 'text':
              identity = telepot.message_identifier(msg)
              bot.editMessageText(identity, "edited")

```

**Comment by nickoala** [comment]
Oh, sorry. Now I realize that you are trying to edit the *sender's* message. The bot, being the recipient, of course cannot edit it. It can only edit its own messages.

**Comment by Blank517** [comment]
I'm sorry I wrongly wrote the code. I just realized my mistake, thanks anyway
