### ISSUE TITLE
Mismatched File Type Error - sendAudio

### ISSUE THREAD

**Issue by rescindable** [nickoala/telepot#228]
Basically I have an option to store and resend audio messages by fileID, using the msg['voice']['file_id'] object the message JSON data returns, but when I try and send the audio using the file ID it always throws a mismatched file type error, as shown:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 781, in collector
    callback(item)
  File "Bot.py", line 4469, in handle
    bot.sendAudio(testGroup, messageAudioID)
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 458, in sendAudio
    return self._sendfile(audio, 'audio', p)
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 425, in _sendfile
    return self._api_request(method, _rectify(params))
  File "/usr/local/lib/python3.5/dist-packages/telepot/__init__.py", line 397, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python3.5/dist-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelgramError: ('Bad Request: type of file mismatch', 400, {'ok': False, 'description': 'Bad Request: type of file mismatch', 'error_code': 400})
```

I receive the same error when I try to send it as a regular file though, so is there something I'm missing here?

The relevant code looks like this:

```
import telepot
import time


def handle(msg):
    if 'voice' in msg:
        isAudio = True
        messageAudioID = msg['voice']['file_id']
    else:
        isAudio = False
    
    testGroup = <location ID string>

    if isAudio:
        bot.sendAudio(testGroup, messageAudioID)

bot = telepot.Bot(<API token>)

bot.message_loop(handle)

while 1:
    time.sleep(100)
```

**Comment by rescindable** [comment]
Aaaand I just read far enough to see that audio and voice are two different objects, I haven't had to deal with audio vs voice objects much so I didn't realize there was distinction, though well there should be. 

My apologies for not researching more carefully.
