### ISSUE TITLE
sendDocument results in empty json

### ISSUE THREAD

**Issue by PoloB12** [nickoala/telepot#256]
Anybody else having issues sending documents ? Since this morning I only get empty json back which results in an ValueError , nothing changed in code, yesterday everything fine ?

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telepot/api.py", line 110, in _parse
    data = json.loads(text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telepot/__init__.py", line 871, in collector
    callback(item)
  File "bot.py", line 114, in handle
    bot.sendDocument(chat_id, document=open('some_file_which_exists', 'rb'))
  File "/usr/local/lib/python3.4/dist-packages/telepot/__init__.py", line 507, in sendDocument
    return self._sendfile(document, 'document', p)
  File "/usr/local/lib/python3.4/dist-packages/telepot/__init__.py", line 466, in _sendfile
    return self._api_request(method, _rectify(params), files)
  File "/usr/local/lib/python3.4/dist-packages/telepot/__init__.py", line 434, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python3.4/dist-packages/telepot/api.py", line 112, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
telepot.exception.BadHTTPResponse: <unprintable BadHTTPResponse object>

**Comment by xkord** [comment]
I have the same issue, how to solve it?
