### ISSUE TITLE
AttributeError: module 'aiohttp.helpers' has no attribute 'FormData'

### ISSUE THREAD

**Issue by wodim** [nickoala/telepot#277]
Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/telepot/aio/__init__.py", line 434, in get_from_telegram_server
        result = await self.getUpdates(offset=offset, timeout=timeout)
      File "/usr/local/lib/python3.5/dist-packages/telepot/aio/__init__.py", line 298, in getUpdates
        return await self._api_request('getUpdates', _rectify(p))
      File "/usr/local/lib/python3.5/dist-packages/telepot/aio/__init__.py", line 65, in _api_request
        return await api.request((self._token, method, params, files), **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/telepot/aio/api.py", line 100, in request
        fn, args, kwargs, timeout = _transform(req, **user_kw)
      File "/usr/local/lib/python3.5/dist-packages/telepot/aio/api.py", line 62, in _transform
        data = _compose_data(req, **user_kw)
      File "/usr/local/lib/python3.5/dist-packages/telepot/aio/api.py", line 39, in _compose_data
        data = aiohttp.helpers.FormData()
    AttributeError: module 'aiohttp.helpers' has no attribute 'FormData'

Is this my fault or just incompatible versions of aiohttp and telepot? I have aiohttp 2.2.5 and telepot 10.2

**Comment by wodim** [comment]
My bad. That was an old version of telepot :-) No clue why pip downloaded that one.
