### ISSUE TITLE
can't use glance on game callback query

### ISSUE THREAD

**Issue by tokke100** [nickoala/telepot#284]
It looks like the button doesn't send back a data variable

edit: The error

pi@raspberrypi:/etc $ python test.py
Listening ...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/loop.py", line 37, in run_forever
    self._handle(msg)
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 1031, in route
    return fn(msg, *args, **kwargs)
  File "test.py", line 17, in on_callback_query
    query_id, from_id= telepot.glance(msg, flavor='callback_query')
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 162, in glance
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 132, in gl_callback_query
    return msg['id'], msg['from']['id'], msg['data']
KeyError: 'data'

**Comment by nickoala** [comment]
Just checked the Bot API docs, the field `data` is indeed optional, although I am not sure when a callback query does *not* have `data`.

That being said, you can always catch the KeyError and extract the first two values manually. :smile:

I am hesitant to call this a *bug* ... because in most cases `data` would be present and it's one thing you almost always have to look up. For cases where it is absent, you can catch the KeyError or just extract the values manually. Sorry for the inconvenience.

Can you tell me *when* `data` would be absent?
