### ISSUE TITLE
skeletona_route.py

### ISSUE THREAD

**Issue by bahmanshadmehr** [nickoala/telepot#296]
Hi  
when I'm executing this code and using inline mode, each time that I press b it gives me an error:
<br />
<br />
Computing for: b
Task exception was never retrieved
future: <Task finished coro=<Answerer.answer.<locals>.compute_and_answer() done, defined at C:\Program Files\Anaconda3\lib\site-packages\telepot\aio\helper.py:100> exception=TelegramError('Bad Request: START_PARAM_INVALID', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: START_PARAM_INVALID'})>
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\telepot\aio\helper.py", line 111, in compute_and_answer
    await self._bot.answerInlineQuery(query_id, **ans)
  File "C:\Program Files\Anaconda3\lib\site-packages\telepot\aio\__init__.py", line 508, in answerInlineQuery
    return await self._api_request('answerInlineQuery', _rectify(p))
  File "C:\Program Files\Anaconda3\lib\site-packages\telepot\aio\__init__.py", line 75, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\telepot\aio\api.py", line 128, in request
    return await _parse(r)
  File "C:\Program Files\Anaconda3\lib\site-packages\telepot\aio\api.py", line 116, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: START_PARAM_INVALID', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: START_PARAM_INVALID'})

**Comment by nickoala** [comment]
Thanks. It's because of [this line](https://github.com/nickoala/telepot/blob/617cae29a2a892650007bc0fbd77fc0d598f65f7/examples/simple/skeletona_route.py#L114):

```python
return dict(results=results, switch_pm_text='Back to Bot', switch_pm_parameter='Optional start parameter')
```

The value of `switch_pm_parameter` should not have spaces. I will update the code soon.
