### ISSUE TITLE
ImportError: No module named urllib3

### ISSUE THREAD

**Issue by ColinTheShark** [nickoala/telepot#338]
I am trying to test out the  simple echobot sript on my computer.
I'm getting the response from the title after I placed a small script to test the bot into the downloaded `telepot-master` folder.
```
import telepot
bot= telepot.Bot('<myToken>')
bot.getMe()
```
I try to start the script inside of PyScripter but it opens up the `api.py` and tells me `ImportError: No module named urllib3`.
Any help on that one?
BTW: total noob in python :D

**Comment by das7pad** [comment]
Run this command to install `telepot` and its requirements:
```
$ pip3 install telepot
```

**Comment by ColinTheShark** [comment]
Yeah, I'm having python2.7 installed on my computer (windows 10)

I have managed to install python2.7 and telepot properly on my uberspace.de
This is the error I am now getting for the echobot.py example from [here](https://www.codementor.io/garethdwyer/building-a-telegram-bot-using-python-part-1-goi5fncay).
```
[colints@finlay ~]$ python echobot.py
Traceback (most recent call last):
  File "echobot.py", line 62, in <module>
    main()
  File "echobot.py", line 54, in main
    text, chat = get_last_chat_id_and_text(get_updates())
  File "echobot.py", line 34, in get_updates
    js = get_json_from_url(url)
  File "echobot.py", line 28, in get_json_from_url
    js = json.loads(content)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by das7pad** [comment]
@ColinTheShark the script you linked to does not use telepot. You could use the comment section there to get help with the script.
