### ISSUE TITLE
Traceback Error in run_forever

### ISSUE THREAD

**Issue by BrunoMonteiro92** [nickoala/telepot#341]
Hi, I developed this bot using telepot

https://ideone.com/mGPwxC

But I keep getting this error message 

`Traceback (most recent call last):
  File "/app/.heroku/src/telepot/telepot/loop.py", line 37, in run_forever
     self._handle(msg)
  File "vlad_bot.py", line 22, in handle
     command = msg['text']
KeyError: 'text'`

Apparently there is no trigger to this, it keeps poping out of nowhere on the logs, but the bot works perfectly, what is causing this error?

**Comment by das7pad** [comment]
Not every Update is a text message, other message types are not required to contain an empty `text` field. See [the documentation entry for `Messages`](https://core.telegram.org/bots/api#message).
> Field | Type | Description
> -- | -- | --
> text | String | Optional. For text messages, ...

---

You could filter text messages in line 21:

```python

def handle(msg):
    if 'text' not in msg:
        return

    chat_id = msg['chat']['id']
```
