### ISSUE TITLE
Bot stops receiving updates after error

### ISSUE THREAD

**Issue by CrocutaCrocuta** [nickoala/telepot#342]
Traceback:

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/loop.py", line 60, in run_forever
    allowed_updates=allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 993, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 136, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
BadHTTPResponse: (502, u'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.12.2</center>\r\n</body>\r\n</html>\r\n', <urllib3.response.HTTPResponse object at 0x7f2cd111fed0>)
`
API version 12.5, installed via PIP.

**Comment by das7pad** [comment]
Hello @CrocutaCrocuta,

the loop is put [on hold for 30 seconds](https://github.com/nickoala/telepot/blob/a3be51e76851bfa58a63f767223e87f02acee5c8/telepot/loop.py#L70..L75) in the shown case, but should continue to pull updates later on.

Can you confirm that it just prints the error and continues to receive updates after the delay?

**Comment by icebergyy** [comment]
I've had the same issue lately.  Can I shorten that 30 second time?

**Comment by lucidBrot** [comment]
Just had the same issue. My bot did not respond for two days. Interestingly, when I tried to abort the command and start the bot again - using CTRL+C - it suddenly started pulling updates again instead of being aborted.
