### ISSUE TITLE
Bot get Telegram API 404 NotFound after telepot upgrade

### ISSUE THREAD

**Issue by acabrol** [nickoala/telepot#350]
Dear i upgraded telepot for my bot and now Telegram API return 404 for getUpdates method i tried to reach the function directly in a web browser ant it works properly 200.

My bot code is at https://github.com/soprasteria/cybersecurity-dfm/blob/master/utils/dfmtelegrambot.py

My test:
- downgrade to version 10.0 telepot but no success
- direct URL test 
https://api.telegram.org/botxxx/getUpdates return 200 with content
- token renewal didn't fix it
- tested on 2 different servers same issue

Here under the log
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 787, in get_fro
_telegram_server
    result = self.getUpdates(offset=offset, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 630, in getUpda
es
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 398, in _api_re
uest
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u'Not Found', 404, {u'error_code': 404, u'ok': False, u'description': u'N
t Found'})`

**Comment by acabrol** [comment]
The bug is fixed that was config issue.

**Comment by kmein** [comment]
@acabrol Could you elaborate on what your "config issue" was? I'm having the same problem right now
