### ISSUE TITLE
Error message appears after a period of time

### ISSUE THREAD

**Issue by codingsett** [nickoala/telepot#351]
Hello i have encountered this error a couple of times while running the bot and it makes the bot stop working....why does this happen and how can i fix it?

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telepot\loop.py", line 60, in run_forever
    allowed_updates=allowed_updates)
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 909, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 434, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python34\lib\site-packages\telepot\api.py", line 154, in request
    r = fn(*args, **kwargs)  # fn must be thread-safe
  File "C:\Python34\lib\site-packages\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python34\lib\site-packages\urllib3\poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=50)

**Comment by nickoala** [comment]
Just a guess, probably related to #239 and #242. Can't provide much assistance there though, sorry.
