### ISSUE TITLE
UnauthorizedError: (u'Unauthorized', 401, {u'error_code': 401, u'ok': False, u'description': u'Unauthorized'})

### ISSUE THREAD

**Issue by lippih** [nickoala/telepot#365]
I followed all instructions for the simple example "diceyclock.py" on raspbery pi, but I get following error:

pi@raspberrypi:~ $ sudo python botroll.py
I am listening ...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/loop.py", line 60, in run_forever
    allowed_updates=allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 993, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 147, in _parse
    raise e(description, error_code, data)
UnauthorizedError: (u'Unauthorized', 401, {u'error_code': 401, u'ok': False, u'description': u'Unauthorized'})

can someone tell me what it means?
thank you

**Comment by lippih** [comment]
Oh no, sorry! I found the error: When copy the Token I forgot the first number ...
