### ISSUE TITLE
[aio.api] Incomplete cleanup of the connection pools

### ISSUE THREAD

**Issue by das7pad** [nickoala/telepot#393]
https://github.com/nickoala/telepot/blob/3792fde251d0f1d5a6ca16c8ad1a71f89360c41d/telepot/aio/api.py#L43

The cleanup was buggy before and got even worse now, as this change https://github.com/nickoala/telepot/commit/3792fde251d0f1d5a6ca16c8ad1a71f89360c41d delays the cleanup even further by scheduling new asyncio tasks.

The gc may collect the session before the cleanup tasks of telepot run.

See this simple demo snippet:
```
rm -rf /tmp/venv/
python3.5 -m venv /tmp/venv
/tmp/venv/bin/pip install telepot==12.7
/tmp/venv/bin/python
import asyncio
import telepot.aio
bot = telepot.aio.Bot('demo')
loop = asyncio.get_event_loop()
loop.run_until_complete(bot.getMe())
exit()
```

Skipping the first few lines of the output:
```
>>> exit()
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7fac050f14e0>>
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.5/site-packages/aiohttp/client.py", line 170, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method BaseConnector.__del__ of <aiohttp.connector.TCPConnector object at 0x7fac06676ef0>>
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.5/site-packages/aiohttp/connector.py", line 213, in __del__
  File "/tmp/venv/lib/python3.5/site-packages/aiohttp/connector.py", line 662, in close
  File "/tmp/venv/lib/python3.5/site-packages/aiohttp/connector.py", line 341, in close
  File "/tmp/venv/lib/python3.5/site-packages/aiohttp/client_proto.py", line 51, in close
  File "/usr/local/lib/python3.5/asyncio/sslproto.py", line 326, in close
  File "/usr/local/lib/python3.5/asyncio/sslproto.py", line 557, in _start_shutdown
  File "/usr/local/lib/python3.5/asyncio/sslproto.py", line 562, in _write_appdata
  File "/usr/local/lib/python3.5/asyncio/sslproto.py", line 667, in _process_write_backlog
  File "/usr/local/lib/python3.5/asyncio/sslproto.py", line 674, in _fatal_error
AttributeError: 'NoneType' object has no attribute '_FATAL_ERROR_IGNORE'
```

The cleanup must take place in an earlier stage of the program exit.

**Comment by nickoala** [comment]
You are correct. I didn't really solve the problem there. In any case, it will be fixed in the next release, whenever that will be.
