### ISSUE TITLE
Unable to add bot in supergroup

### ISSUE THREAD

**Issue by eatcodesleep** [nickoala/telepot#4]
I'm unable to add the bot in super groups.

I get the following error.

Method: channels.inviteToChannel
Result: {"_":"rpc_error","error_code":400,"error_message":"CHAT_ADMIN_REQUIRED"}
Stack: Error
    at u (https://web.telegram.org/js/app.js:18:3697)
    at https://web.telegram.org/js/app.js:18:4996
    at l (https://web.telegram.org/js/app.js:8:11738)
    at https://web.telegram.org/js/app.js:8:11910
    at m.$eval (https://web.telegram.org/js/app.js:8:19316)
    at m.$digest (https://web.telegram.org/js/app.js:8:17747)
    at https://web.telegram.org/js/app.js:8:19403
    at a (https://web.telegram.org/js/app.js:7:2845)
    at https://web.telegram.org/js/app.js:7:4299
    at n (https://web.telegram.org/js/app.js:2:17073)

**Comment by nickoala** [comment]
What does this have to do with Telegram Bot in general, or telepot in particular?
