### ISSUE TITLE
glance fails with `Cannot infer content type from message` if emoji in user name

### ISSUE THREAD

**Issue by zumoshi** [nickoala/telepot#42]
Hello, 

so basically put an emoji in your name (doesn't matter first or last) than pm your bot and it explodes :|

reproduction code:
```
import telepot
bot = telepot.Bot('token')

updates = bot.getUpdates()
for msg in updates:
	content_type, chat_type, chat_id = telepot.glance(msg)
	print(chat_id)
```

stack trace:
```
Traceback (most recent call last):
  File "emobug.py", line 6, in <module>
    content_type, chat_type, chat_id = telepot.glance(msg)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 68, in glance
    return gl_message()
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 51, in gl_message
    content_type = _infer_content_type(msg)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 44, in _infer_content_type
    raise RuntimeError('Cannot infer content type from message', msg)
RuntimeError: ('Cannot infer content type from message', {'message': {'chat': {'type': 'private', 'first_name': 'Bor', 'last_name': '691\U0001f631', 'id': 61412354, 'username': '------'}, 'date': 1459066867, 'text': 'my name has an emoji', 'message_id': 157, 'from': {'first_name': 'Bor', 'last_name': '691\U0001f631', 'id': 61412354, 'username': '------'}}, 'update_id': 816132183})

```

the formatting thing from the other issue would've came in handy in here too. i'm looking forward for that one.

thanks in advance 

---

update , seems like i have made a mistake in my reproduction code , and in fact telepot can handle messages with emoji in user name correctly , this is the main trace i got in main project (which i failed miserably in isolating it... )

```
Traceback (most recent call last):
  File "C:\w\bot\support\src\bot.py", line 23, in index
    bot.handle(cherrypy.request.json['message'])
  File "C:\w\bot\support\src\botsaz.py", line 31, in handle
    content_type, chat_type, chat_id = telepot.glance(msg)
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 68, in glance
    return gl_message()
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 51, in gl_message
    content_type = _infer_content_type(msg)
  File "C:\Python34\lib\site-packages\telepot\__init__.py", line 44, in _infer_content_type
    raise RuntimeError('Cannot infer content type from message', msg)
RuntimeError: ('Cannot infer content type from message', {'chat': {'type': 'supergroup', 'id': -1001033794483, 'title': '😍 groupname💦'}, 'date': 1459065099, 'message_id': 3328, 'from': {'first_name': '🔰K E E P E R🔰™', 'username': '(removed)', 'id': 157123872}})
```

since i recently had other issues with emojis i assumed it was because of emojis in his name , but now that i look closer the json is in fact incomplete and lacks all message types . my bad.
i'll investigate further in my own code to see why it is missing required keys.

**Comment by nickoala** [comment]
@zumoshi , you are testing my code more thoroughly than I ever have. Telepot is becoming more robust because of you. Thank you.

By the way, is that a roasted fish in your photo?

**Comment by zumoshi** [comment]
yes , i was in a coastal city in turkey at a restaurant that served fresh fish , one of my family members that was with me at the time was really disgusted by the look of fish's head O.o so i took a picture of it :D 

do you have any idea why the update object would be missing all the content types as displayed in the trace back from real app ?

**Comment by nickoala** [comment]
Yes, that picture is ugly. I'd rather you change it. :smile: 

Are you using webhook?

**Comment by zumoshi** [comment]
yes, i am using cherrypy and a custom controller that passes requests to handle function which looks like this:

```
@cherrypy.expose
    @cherrypy.tools.json_in()
    def index(self, token):
        if token in self.me.bots:
            bot = self.me.bots[token]
            bot_info = bot.bot
            if 'expire' in bot_info and bot_info['expire'] < datetime.now():
                print('expire')
            elif 'disabled' in bot_info:
                print('bot_disabled')
            else:
                try:
                    bot.handle(cherrypy.request.json['message'])
                except:
                    self.me.report_bug(traceback.format_exc())
                    raise
        else:
            print("unknown bot")
        return "OK"
```

this was my first guess too , that perhaps there was something outside of `message` key that was not sent to the handle function , but i checked all the cases (e.g. group changed to super group notification , user joined group notification , ...) all of them have keys in the `message` which is clearly sent to the handle function completely (without any modification).

**Comment by nickoala** [comment]
Perhaps the webhook is receiving some [InlineQuery](https://core.telegram.org/bots/api#inlinequery) or [ChosenInlineResult](https://core.telegram.org/bots/api#choseninlineresult). [Update](https://core.telegram.org/bots/api#update) may contain one of the three, with different keys. In other words, I think you should check whether the `message` field is present before passing it to the bot.

In case you haven't noticed, telepot has a **[webhook interface](https://github.com/nickoala/telepot#webhook-interface)**. Maybe you can consider that.

The way you call `bot.handle()` alarms me a little bit. I know little about CherryPy, but if it spawns a thread per request, that means your `bot.handle()` has to be thread-safe. You just have to be careful how CherryPy deals with many requests at the same time.

If you use telepot's **webhook interface**, then you don't have to worry about that, because it uses a synchronized queue to pass messages to the bot.

**Comment by zumoshi** [comment]
i thought that too , but i believe `message` field  won't be present in event of an inline query , in which case i would've received a `keyerror` before handle function was even invoked , not the error i got.

in my case message field was present but was incomplete which is strange.

i am aware of the thread safety issues , thanks for bringing it up though. at the moment my bot doesn't get enough traffic for it to be a concern but if i encountered errors i plan to refactor the code to use async functions and i'll probably use telepot delegate queue system so i can leverage context awareness too , but it seems too much work at the moment and i'm not sure if its worth it for this bot.

**Comment by nickoala** [comment]
Then, I guess the only way is to log every request and see what they contain. But I am sure you have thought of that and may be doing it right now.

**Comment by zumoshi** [comment]
it only happened once , and i failed to reproduce it myself.
i sent a pm to the person that caused the exception but even with his help i was still unable to reproduce it. so for the time being i decided to just ignore this error , i've added the following to my code:

```python
        try:
            content_type, chat_type, chat_id = telepot.glance(msg)
        except RuntimeError:
            return
```

i know this isn't the right way to handle this but it doesn't seem to cause any problems with the bot's legitimate usage. basically i just ignore all messages which glance can't handle and return `200 OK` for telegram bot api.
