### ISSUE TITLE
Error download video - file is too big

### ISSUE THREAD

**Issue by fortunto2** [nickoala/telepot#52]
Hi
Why files are uploaded in messenger  but not downloaded in telepot ?
Limit in telegrams  above 1.5G?

`
{u'duration': 0, u'width': 0, u'file_size': 89704028, u'file_id': u'BAADAgADGwADIiE6********', u'height': 0}

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 338, in handle
    callback(update['message'])
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 293, in route
    fn(msg, *args)
  File "./bot.py", line 27, in on_chat_message
    bot.downloadFile(video_id, '/home/rustam/bot/'+video_id+'.mp4')
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 300, in downloadFile
    f = self.getFile(file_id)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 274, in getFile
    return self._parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 179, in _parse
    raise TelegramError(description, error_code, data)
TelegramError: (u'[Error]: Bad Request: file is too big[size:89704028]', 400, {u'error_code': 400, u'ok': False, u'description': u'[
Error]: Bad Request: file is too big[size:89704028]'})
`

**Comment by zumoshi** [comment]
Hello,
this is a Telegram Bot Api limitation:
> For the moment, bots can download files of up to 20MB in size.

source: https://core.telegram.org/bots/api#getfile

**Comment by fortunto2** [comment]
thanks, very bad(((
you have not heard , when they can increase the limit ?

**Comment by nickoala** [comment]
Well, you have to ask Telegram for that. I don't have an answer.
