### ISSUE TITLE
Telepot doesn't handle well to loose connection

### ISSUE THREAD

**Issue by gbarba** [nickoala/telepot#53]
Hi,
if the machine where telepot bot is running looses its connection (with telegram) it enters to an infinite loop until it recover connection if it happens:

```
Traceback (most recent call last):
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 769, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 641, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 304, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=50)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guillem/metis/repos/telepot/telepot/__init__.py", line 356, in get_from_telegram_server
    result = self.getUpdates(offset=offset, timeout=timeout)
  File "/home/guillem/metis/repos/telepot/telepot/__init__.py", line 280, in getUpdates
    timeout=self._http_timeout+(0 if timeout is None else timeout))
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=50)
Traceback (most recent call last):
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/guillem/.virtualenvs/improviders/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:
```
(and repeat ReadTimeoutError exception + socket.gaierror again and again)

The problem is [this loop](https://github.com/nickoala/telepot/blob/ba453c784eb2a0599889ce66710a694874ef5f8b/telepot/__init__.py#L354) that doesn't have any end condition.

Before start a PR, is this situation expected to be managed in some way?
My solution will be to have a new param in notifyOnMessage() with the number of attempts (by default, 5, for example).
In the except (or finally) of the loop, it discounts an attempt and if it is less or equal to 0 it breaks the loop.
It should stop the main thread which can be done sending an interruption signal to main thread:
```
os.kill(os.getpid(), signal.SIGINT)
```

**Comment by nickoala** [comment]
In this case, it *is* my intention to loop indefinitely. When you tell it to get messages for you, shouldn't it keep trying relentlessly? Suppose Telegram servers resume normal operations after 10 minutes, or you re-plug the network cable after a while, shouldn't the bot resume normal operations too? If the bot, as you suggested, commits suicide after a number of failed attempts, then it will have to be re-started after every brief period of network outage? Is that really what you want?

Your suggestion to add a param (the number of attempts) is reasonable, but is it useful?

**Comment by zumoshi** [comment]
I agree that infinite loop is better , it should have `sleep` or similar delay before each try to prevent high cpu usage, say retry each 1 second* , but it should not stop.
i would also like retry on other commands (other than getUpdates) if failure was network based and not a telegram error. (due bad connection on my development machine i randomly get anything from timeouts to `SSLError` when invoking methods)


*as i understand the code a relax time is applied however it is applied independent of whether call was successful or erroneous. since the timeout parameter to get updates already prevents rapid connections perhaps we should only apply it when an error happens or when `timeout < relax` ?

**Comment by nickoala** [comment]
@zumoshi, I thought about retry some time ago, but decided it was unimportant enough. Now that you've brought it up, let me tell you what I think.

The desire to retry on some failures is actually a very general problem, not restricted to telepot, not even restricted to network ops. And that desire is a very top-down thing. That's why I was reticent to embed retry logic in telepot.

A general problem requires a general solution - a piece of code which you can take with you to apply to whatever retry situations you want, without being tied to any particular library.

The following piece of code demonstrates what I mean. In `retry`, you decide **how many times** you want to retry **on what type of errors** (e.g. `retry(1, [KeyError])`). You take the result, and wrap that on an unreliable function (e.g. `retry(1, [KeyError])(erratic)`), before actually making the call:

```python
def retry(times, on_errors):
    def make_loop(fn):
        def w(*args, **kwargs):
            for i in range(0, times+1):
                try:
                    return fn(*args, **kwargs)
                except tuple(on_errors):
                    print('Called %d times' % (i+1))
                    pass
                except:
                    raise  # unexpected error
            raise  # retry too many times
        return w
    return make_loop

import random
def erratic():
    i = random.randint(0,2)
    if i == 0:
        print('True')
        return True
    elif i == 1:
        print('KeyError')
        raise KeyError()
    else:
        print('RuntimeError')
        raise RuntimeError()

retry(1, [KeyError])(erratic)()
```

Run the code. You'll see what I mean.

It is possible for telepot to provide a similar function. It would be a nice addition. Imagine making such a call:

```python
telepot.http_retry(3)(bot.sendMessage)(chat_id, 'Hello')
```

In fact, I think you can make small modifications to that piece of code, decide on which type of errors you want to retry on, and use it right away.

**Comment by gbarba** [comment]
@nickoala I accept your arguments. At the end, implement my version of notifyOnMessage() is trivial and I can implement there my own behaviour.

The piece of code or "retry" is very nice! I will include in my "utils".

For me, this issue can be closed
