### ISSUE TITLE
TypeError: answerInlineQuery() got an unexpected keyword argument 'gif_url'

### ISSUE THREAD

**Issue by pituseligmann** [nickoala/telepot#61]
Hello there!

Im trying to set up a bot using Telepot that returns a series of inline gifs for the user to choose based on the keyword he sent. I based the code on the examples proposed on the Telepot readme, so the method that's not working right is the next one.

```
def on_inline_query(msg):
    def compute_answer():
        query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
        print 'Computing for: %s' % query_string

        response = {}

        # This function returns a list of urls pointing to gifs, all under 1mb.
        gifs = search_gif('gif {}'.format(query_string))
        
        for gif in gifs:
                # example of the first gif: https://45.media.tumblr.com/cafa4bb1b2a869b556ee57fe592213db/tumblr_o5vabtnqz21t1bfwbo7_r2_250.gif
                response.update({'type': 'gif','id': 'abc', 'gif_url':gif, 'thumb_url':gif})

        print response
        return response

    answerer.answer(msg, compute_answer)
```

With this code, I'm printing the response just to check it to debug, and it's throwing an error on the first iteration which is:

```
{'gif_url': u'https://45.media.tumblr.com/cafa4bb1b2a869b556ee57fe592213db/tumblr_o5vabtnqz21t1bfwbo7_r2_250.gif', 'thumb_url': u'https://45.media.tumblr.com/cafa4bb1b2a869b556ee57fe592213db/tumblr_o5vabtnqz21t1bfwbo7_r2_250.gif', 'type': 'gif', 'id': 'abc'}

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 171, in run
    outerself._bot.answerInlineQuery(query_id, **ans)
TypeError: answerInlineQuery() got an unexpected keyword argument 'gif_url'
```

Any ideas as to what would be causing this?
Thank you very much!

**Comment by zumoshi** [comment]
Hello,
you have a mistake in your code , `response` should be a `list` not a `dict`. by updating the response you are just overwriting the next gif on the previous one.

just change the response to a list and change the line to use `response.append` instead of `update`:

```python
def on_inline_query(msg):
    def compute_answer():
        query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
        print ('Computing for: %s' % query_string)

        response = []

        # This function returns a list of urls pointing to gifs, all under 1mb.
        gifs = search_gif('gif {}'.format(query_string))

        for gif in gifs:
                # example of the first gif: https://45.media.tumblr.com/cafa4bb1b2a869b556ee57fe592213db/tumblr_o5vabtnqz21t1bfwbo7_r2_250.gif
                response.append({'type': 'gif','id': 'abc', 'gif_url':gif, 'thumb_url':gif})

        print (response)
        return response

    answerer.answer(msg, compute_answer)
```

**Comment by pituseligmann** [comment]
Oh man, I feel dumb now! That was indeed it, can't believe I missed it. 

As of now, I'm sending 10 items per request, would it be possible that once the user gets to the end by swiping/scrolling to trigger a callback or something and send the next 10 items?. I was reading the docs on telepot but still haven't found a way to do this.

Thanks!

**Comment by zumoshi** [comment]
no problem, happens to the best of us :)

yes you can paginate your results for an inline query, refer to the bot api manual when telepot's docs are not enough, telepot is just a wrapper around them:
https://core.telegram.org/bots/api#answerinlinequery

as you can see in the manual `next_offset` key is what you want, telepot supports this paramter, from the [Reference](https://github.com/nickoala/telepot/blob/master/REFERENCE.md#telepot-Bot):
```python
answerInlineQuery(inline_query_id, results, cache_time=None, is_personal=None, next_offset=None)
```

however you are using the Answerer helper class, so we can return the `next_offset` parameter from our `compute_answer` method, we just have to return a dict:
```python
def on_inline_query(msg):
    def compute_answer():
        query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
        print('Computing for: %s' % query_string)

        # offset is initially an empty string
        offset = int(msg['offset']) if msg['offset'] != '' else 0

        response = []

        # This function returns a list of urls pointing to gifs, all under 1mb.
        # use offset here to get the correct results, perhaps modify search_gif
        # to accept offset as an additional parameter?
        gifs = search_gif('gif {}'.format(query_string), offset)

        for id, gif in enumerate(gifs):
            # example of the first gif: https://45.media.tumblr.com/cafa4bb1b2a869b556ee57fe592213db/tumblr_o5vabtnqz21t1bfwbo7_r2_250.gif
            # i've changed this line to create unique id's
            response.append({'type': 'gif', 'id': 'gif_' + str(offset + id), 'gif_url': gif, 'thumb_url': gif})

        if len(gifs) < 10:
            # seems we ran out of gifs , set offset to '' to signal telegram
            # that we have no more results
            offset = ''
        else:
            # set offset as page number
            offset = str(offset + 1)

        print(response)
        # here instead of just sending the response, we send a dict with results and next_offset
        # you can also specify cache_time and is_personal parameters here
        return {'results': response, 'next_offset': offset}

    answerer.answer(msg, compute_answer)
```
more info on the [Answerer class in the Reference](https://github.com/nickoala/telepot/blob/master/REFERENCE.md#telepot-helper-Answerer).

**Comment by nickoala** [comment]
@zumoshi, thank you. I appreciate it.

**Comment by pituseligmann** [comment]
@zumoshi I gotta thank you man, you've made it so clear! I now understand what I was missing when trying to make the offset thingy. Thanks!
