### ISSUE TITLE
Asyncio version bot gracefull shutdown

### ISSUE THREAD

**Issue by phrolov** [nickoala/telepot#69]
Is there any way to proper close bot underlying session and loop? I got errors on program exit:

```
2016-04-28 19:53:01,396: ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<Bot.message_loop() running at /usr/local/lib/python3.5/site-packages/telepot/async/__init__.py:461> wait_for=<Future pending cb=[Task._wakeup()]>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
GeneratorExit
Exception ignored in: <generator object Bot.message_loop at 0x107174d00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/telepot/async/__init__.py", line 461, in message_loop
    yield from get_from_telegram_server()
  File "/usr/local/lib/python3.5/site-packages/telepot/async/__init__.py", line 353, in get_from_telegram_server
    yield from asyncio.sleep(0.1)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 506, in sleep
    future, result)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 412, in call_later
    timer = self.call_at(self.time() + delay, callback, *args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 425, in call_at
    self._check_closed()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by nickoala** [comment]
Hi @phrolov, I currently don't have an answer on that, because I have some higher-priority issues to look at. My suggestion is, can you enclose your entire application in a `try ... except ...`, and catch whatever exceptions it throws?

I know this is not an "ideal" solution, but hey, this is something that happens just before it dies .... so .... I hope that does it for you.

**Comment by CzBiX** [comment]
Any updates?
