### ISSUE TITLE
Thread exception

### ISSUE THREAD

**Issue by aRandomStranger** [nickoala/telepot#72]
Hi there,

so i tried to setup an example Bot but after i wanted to run it, following exception got reported:

`Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 437, in get_from_telegram_server
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'`

Well that looks really strange for me.

**Comment by nickoala** [comment]
That line is this:
```python
time.sleep(relax)
```
And the exception indicates that `time` is `None`, so doesn't have an attribute `sleep`.

Do you have any file in `PYTHONPATH` named `time.py`?
