### ISSUE TITLE
Error while running  webhook_flask_counter

### ISSUE THREAD

**Issue by vivek425ster** [nickoala/telepot#78]
Hi, 
I am trying to run webhook_flask_counter on my localhost. This is the paramter which i am passing
``python webhook_flask_counter.py token 8443 localhost:8443/abc``
Traceback
```Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telepot/__init__.py", line 479, in get_from_queue
    update = dictify(data)
  File "/Library/Python/2.7/site-packages/telepot/__init__.py", line 451, in dictify27
    return json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")```

 This happens when I send a request to /abc 

Thanks

**Comment by nickoala** [comment]
Please see issue #60 - Running webhook_flask_skeleton.py locally
