### ISSUE TITLE
Does this support proxy servers?

### ISSUE THREAD

**Issue by dazzag24** [nickoala/telepot#88]
I can't see where one would specify the proxy server details.  Does it use the system environment proxy details (http_proxy, https_proxy)?

foo@blah:~/code/telepot$ python 
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import telepot
>>> bot = telepot.Bot('XXXXXXXXX:ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ')
>>> bot.getMe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 170, in getMe
    return self._api_request('getMe')
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 167, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 126, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 165, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 604, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:590)

**Comment by kalety** [comment]
look at #83 ,)

**Comment by dazzag24** [comment]
Thanks.  That works!  From completeness here is the modified version of the "Test the account" code from the https://github.com/nickoala/telepot page.

import urllib3
import telepot
import telepot.api

myproxy_url = 'http://localhost:3128/'

telepot.api._pools = {'default': urllib3.ProxyManager(proxy_url=myproxy_url, num_pools=3, maxsize=10, retries=False, timeout=30),}

telepot.api._onetime_pool_spec = (urllib3.ProxyManager, dict(proxy_url=myproxy_url, num_pools=1, maxsize=1, retries=False, timeout=30))

bot = telepot.Bot(XXXXXXXXX:ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ')
print bot.getMe()
