### ISSUE TITLE
Sending binary data as photo

### ISSUE THREAD

**Issue by p-hash** [nickoala/telepot#98]
I am sending binary data as photo with the code I used in telepot 7 (and it worked)
```python
file_link = 'http://example.com/a.jpg'
image = requests.get(file_link).content
bot.sendPhoto(from_id, ('a.jpg', image))
```

Now I get an assertion error:
```
Traceback (most recent call last):
  .....
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/__init__.py", line 273, in sendPhoto
    return self._sendfile(photo, 'photo', p)
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/__init__.py", line 255, in _sendfile
    return self._api_request(method, _rectify(params), files)
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/__init__.py", line 224, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/api.py", line 129, in request
    fn, args, kwargs = _transform(req, **user_kw)
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/api.py", line 94, in _transform
    fields = _compose_fields(req, **user_kw)
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/api.py", line 60, in _compose_fields
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/api.py", line 60, in <dictcomp>
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/home/paul/.local/lib/python3.5/site-packages/telepot/api.py", line 41, in _filetuple
    return (f[0], f[1].read())
AttributeError: 'bytes' object has no attribute 'read'
```

Is it possible to send photos from binary data or from url in telepot 8?

**Comment by nickoala** [comment]
Can you try:

```python
f = urlopen(file_link)
bot.sendPhoto(from_id, ('a.jpg', f))
```

**Comment by p-hash** [comment]
That worked. Thank you!
